LITRevu/LITRevu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
import blog.views
import authentication.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(
        template_name='authentication/login.html',
        redirect_authenticated_user=True),
        name='login'),
    path('logout/',
         LogoutView.as_view(next_page='login'),
         name='logout'),
    path('home/',
         blog.views.home,
         name='home'),
    path('posts/',
         blog.views.posts,
         name='posts'),
    path('signup/',
         authentication.views.signup_page,
         name='signup'),
    path('create_ticket/',
         blog.views.create_ticket,
         name='create_ticket'),
    path('blog/books/<int:book_id>/',
         blog.views.book_details,
         name='book_details'),
    path('blog/item_details/<str:item_type>/<int:item_id>/',
         blog.views.item_details,
         name='item_details'),
    path('create_review/',
         blog.views.create_review,
         name='create_review'),
    path('relations/',
         blog.views.relations,
         name='relations'),
    path('follow_unfollow/',
         blog.views.follow_unfollow,
         name='follow_unfollow'),
    path('block_unblock/',
         blog.views.block_unblock,
         name='block_unblock'),
    path('stop_following_me/',
         blog.views.stop_following_me,
         name='stop_following_me'),
    path('edit_ticket/<int:ticket_id>/<int:book_id>/',
         blog.views.edit_ticket,
         name='edit_ticket'),
    path('edit_review/<int:review_id>/<int:book_id>/',
         blog.views.edit_review,
         name='edit_review'),
    path('delete_item/<str:item_type>/<int:item_id>/',
         blog.views.delete_item,
         name='delete_item'),
    path('just_book_form/',
         blog.views.just_book_form,
         name="just_book_form"),
    path('create_review_answer_ticket/<int:book_id>/<int:ticket_id>/',
         blog.views.create_review_answer_ticket,
         name='create_review_answer_ticket'),
    path('search_users/',
         blog.utils.search_user_method,
         name='search_users')
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LITRevu/blog/forms.py
from django import forms
from . import models


class CreateTicketForm(forms.ModelForm):
    class Meta:
        model = models.Ticket
        fields = ['author', 'book']
        widgets = {
            'book': forms.HiddenInput(),
            'author': forms.HiddenInput(),
        }


class CreateBookForm(forms.ModelForm):
    title = forms.CharField(required=True)
    author = forms.CharField(required=True)
    date = forms.IntegerField(required=True)
    book_cover = forms.ImageField(required=True)

    class Meta:
        model = models.Book
        fields = ['title', 'author', 'date', 'book_cover', 'submitted_by']
        widgets = {
            'submitted_by': forms.HiddenInput()
        }


class CreateBookOptionalForm(forms.ModelForm):
    title = forms.CharField(required=False)
    author = forms.CharField(required=False)
    date = forms.IntegerField(required=False)
    book_cover = forms.ImageField(required=False)

    class Meta:
        model = models.Book
        fields = ['title', 'author', 'date', 'book_cover', 'submitted_by']
        widgets = {
            'submitted_by': forms.HiddenInput()
        }


class CreateReviewForm(forms.ModelForm):
    class Meta:
        model = models.Review
        fields = ['review_title', 'rating', 'book', 'ticket', 'review_text']
        widgets = {
            'review_text': forms.Textarea(),
        }


class CreateReviewFormAnswerTicket(forms.ModelForm):
    class Meta:
        model = models.Review
        fields = ['review_title', 'rating', 'book', 'ticket', 'review_text']
        widgets = {
            'review_text': forms.Textarea(),
            'book': forms.HiddenInput(),
            'ticket': forms.HiddenInput(),
        }


class EditBookForm(forms.ModelForm):
    title = forms.CharField(required=False)
    author = forms.CharField(required=False)
    date = forms.IntegerField(required=False)
    book_cover = forms.ImageField(required=False)

    class Meta:
        model = models.Book
        fields = ['title', 'author', 'date', 'book_cover']


class EditReviewForm(forms.ModelForm):
    class Meta:
        model = models.Review
        fields = ['review_title', 'rating', 'book', 'ticket', 'review_text']


class SearchUserForm(forms.Form):
    search = forms.CharField(required=False)
    fields = ['search']

LITRevu/blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from authentication import models as auth_models
from django.views.decorators.http import require_http_methods
from .utils import block_unblock_method, stop_following_me_method, follow_unfollow_method

from . import forms, models
import datetime


@login_required
def home(request):
    """
    Displays items regarding relations to other users (blocked, followed etc.),
     and their types (review or tickets) after the homepage rules.
    :param request:
    :return: Sorted feed
    """
    user = request.user
    user_followers = user.followers.all()
    tickets = models.Ticket.objects.all()
    reviews = models.Review.objects.all()
    feed = []
    blocked_by = []
    for blocking_user in user.blocked_by.all():
        blocked_by.append(blocking_user)
    for ticket in tickets:
        ticket_details = (ticket, 'ticket')
        if ticket.author in user_followers or ticket.author == user:
            feed.append(ticket_details)
    for review in reviews:
        review_details = (review, 'review')
        if review.author not in user.blocked_by.all():
            if review.author in user_followers or review.author == user:
                feed.append(review_details)
            if review.ticket:
                if review.ticket.author == user and review_details not in feed:
                    feed.append(review_details)
    sorted_feed = sorted(feed, key=lambda item: item[0].date, reverse=True)
    return render(request, 'blog/home.html',
                  context={'feed': sorted_feed,
                           'user_followers': user_followers,
                           'user': user,
                           }
                  )


@login_required
def posts(request):
    """
    Displays items regarding relations to other users (blocked, followed etc.),
     and their types (review or tickets) after the posts page rules.
    :param request:
    :return: Sorted feed
    """
    current_user = request.user
    tickets = models.Ticket.objects.all()
    reviews = models.Review.objects.all()
    feed = []
    blocked_by = []
    for blocking_user in current_user.blocked_by.all():
        blocked_by.append(blocking_user)
    for ticket in tickets:
        if ticket.author != current_user and ticket.author not in blocked_by:
            ticket_details = (ticket, 'ticket')
            feed.append(ticket_details)
    for review in reviews:
        if review.author != current_user and review.author not in blocked_by:
            review_details = (review, 'review')
            feed.append(review_details)
    sorted_feed = sorted(feed, key=lambda item: item[0].date, reverse=True)
    return render(request, 'blog/home.html',
                  context={'feed': sorted_feed,
                           'user': current_user,
                           }
                  )


@login_required
def create_ticket(request):
    """
    Displays the book creation form to create a ticket. Book information are
    informed by the user and ticket information are automatically created.
    :param request:
    :return: Ticket creation view
    """
    form = forms.CreateBookForm(initial={'submitted_by': request.user})
    if request.method == 'POST':
        form = forms.CreateBookForm(request.POST, request.FILES)
        if form.is_valid():
            now = datetime.datetime.now()
            book_instance = form.save(commit=False)
            book_instance.submitted_by = request.user
            book_instance.save()
            ticket_instance = models.Ticket.objects.create(
                author=request.user,
                book=book_instance,
                date=now
            )
            models.Ticket.objects.filter(id=ticket_instance.id).update(
                date=datetime.datetime.now()
            )
            return render(request, 'blog/ticket_confirmation.html',
                          context={'book': book_instance}
                          )

    return render(request, 'blog/create_ticket.html',
                  context={'form': form}
                  )


@login_required
def create_review(request):
    """
    Displays the review creation form. Book information are selected among
     the existing books or created with an optional book form.
    :param request:
    :return: Review creation view
    """
    review_form = forms.CreateReviewForm()
    book_form = forms.CreateBookOptionalForm(initial={
        'submitted_by': request.user
    })
    if request.method == 'POST':
        review_form = forms.CreateReviewForm(request.POST)
        book_form = forms.CreateBookOptionalForm(
            request.POST,
            request.FILES,
            initial={
                'submitted_by': request.user
            }
        )
        if review_form.is_valid():
            if request.POST['book']:
                review_instance = models.Review.objects.create(
                    author=request.user,
                    date=datetime.datetime.now(),
                    review_title=review_form.cleaned_data['review_title'],
                    rating=review_form.cleaned_data['rating'],
                    book=review_form.cleaned_data['book'],
                    ticket=review_form.cleaned_data['ticket'],
                    review_text=review_form.cleaned_data['review_text'],
                )
                models.Review.objects.filter(id=review_instance.id).update(
                    date=datetime.datetime.now()
                )
            elif book_form.is_valid():
                book_instance = book_form.save()
                review_instance = review_form.save(commit=False)
                review_instance.author = request.user
                review_instance.date = datetime.datetime.now()
                review_instance.book = book_instance
                review_instance.save()
                models.Review.objects.filter(id=review_instance.id).update(
                    date=datetime.datetime.now()
                )

            return redirect('home')

    return render(request, 'blog/create_review.html',
                  context={'review_form': review_form,
                           'book_form': book_form}
                  )


@login_required
def create_review_answer_ticket(request, book_id, ticket_id):
    """
    Displays the review creation form where a book, and a ticket are instantiated.
    :param request:
    :param book_id:Int
        Id of the reviewed book
    :param ticket_id:Int
        Id of the answered ticket
    :retun: Review creation view.
    """
    book = models.Book.objects.get(id=book_id)
    ticket = models.Ticket.objects.get(id=ticket_id)
    review_form = forms.CreateReviewFormAnswerTicket()
    review_form.book = book
    if request.method == 'POST':
        review_form = forms.CreateReviewFormAnswerTicket(request.POST)
        review_form.book = book_id
        if review_form.is_valid():
            review_instance = models.Review.objects.create(
                author=request.user,
                date=datetime.datetime.now(),
                review_title=review_form.cleaned_data['review_title'],
                rating=review_form.cleaned_data['rating'],
                book=book,
                ticket=ticket,
                review_text=review_form.cleaned_data['review_text'],
            )
            models.Review.objects.filter(id=review_instance.id).update(
                date=datetime.datetime.now()
            )
            return redirect('home')
    return render(request, 'blog/create_review_answer_ticket.html',
                  context={'review_form': review_form,
                           'book': book,
                           'ticket': ticket}
                  )


@login_required
def book_details(request, book_id):
    """
    Displays book details, used in various pages (i.e., ticket details
    or review details views)
    :param request:
    :param book_id:Int
        Id of detailed book to display.
    :return: View of book details.
    """
    book = models.Book.objects.get(id=book_id)
    return render(request, 'blog/book_details.html',
                  context={'book': book}
                  )


@login_required
def item_details(request, item_id, item_type):
    """
    Displays the details of the item, whether it is a ticket or a review.
    :param request:
    :param item_id:
    :param item_type:str
        'ticket' or 'review', for templating purposes.
    :return: A detailed page of the item.
    """
    reviews_to_display = []
    if item_type == 'ticket':
        item = models.Ticket.objects.get(id=item_id)
        details_type = 'ticket'
        reviews_to_display = models.Review.objects.all().filter(ticket_id=item_id)
    elif item_type == 'review':
        item = models.Review.objects.get(id=item_id)
        details_type = 'review'
    book = item.book
    return render(request, 'blog/item_details.html',
                  context={'item': item,
                           'book': book,
                           'details_type': details_type,
                           'reviews_to_display': reviews_to_display}
                  )


@login_required
def relations(request):
    """
    Displays the main page to manage the relations between users.
    Displays a search bar where all users can be reached, and all the existing
    foreignkeys between current user and others (blocking / blocked_by,
    and followed by / followed).
    Those relations can be modified in this view.
    :param request:
    :return: Relations page view.
    """
    current_user = request.user
    users = auth_models.User.objects.all()
    public_users = []
    search_form = forms.SearchUserForm()
    for user in users:
        if not user.is_staff:
            public_users.append(user)
    if not current_user.is_staff:
        public_users.remove(current_user)
    sorted_users = sorted(public_users, key=lambda u: u.username)

LITRevu/blog/templates/blog/book_details.html
{% extends 'base.html' %}
{% block content %}
<main class="book_details">
    <h2>Détails de {{ book.title }}</h2>
    <p>{{ book.title }}</p>
    <p>{{ book.date }}</p>
    <p>{{ book.author }}</p>
    <img class="book_cover_details" src="{{ book.book_cover.url }}">
</main>
{% endblock content %}

LITRevu/blog/templates/blog/create_review.html
{% extends 'base.html' %}
{% block content %}
<div class="content-creation-form">
    <h2>Création de reviews</h2>
    <h3>Livre</h3>
    <div class="new-book-toggle-div">Nouveau livre :
        <a href="#">
        <label class="switch"><input type="checkbox" onclick="toggleNewBookForm()">
            <span class="slider round"></span>
        </label>
        </a>
    </div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="review-creation">
        <div id="review_form">{{ review_form.as_p }}</div>
        <div id="new_book_form" style="display:none;"></div>
        </div>
        <button type="submit">Enregistrer la review</button>
    </form>
    <script>
    function toggleNewBookForm() {
        const newBookForm = document.getElementById('new_book_form');
        const book_selector = document.getElementById('review_form').children[2]
        const ticket_selector = document.getElementById('review_form').children[3]
        if (newBookForm.style.display === 'none') {
            newBookForm.style.display = 'block';
            book_selector.style.display = 'none';
            ticket_selector.style.display = 'none';
            fetch('{% url 'just_book_form' %}')
                .then(response => response.text())
                .then(data => newBookForm.innerHTML = data)
        } else {
            newBookForm.style.display = 'none';
            book_selector.style.display = 'block'
            ticket_selector.style.display = 'block';
            newBookForm.innerHTML = 'rien'
        }
    }
    </script>
</div>
{% endblock content %}

LITRevu/blog/templates/blog/create_review_answer_ticket.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <main class="details">
            <div class="user-content">
                <h2>Critique de {{ book.title }}</h2>
                <h3>Demande de critique de la part de : {{ ticket.author }}</h3>
                <div class="rating">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="review-creation">
                        <div>{{ review_form.as_p }}</div>
                        </div>
                        <button type="submit">Enregistrer la review</button>
                    </form>
                </div>
            <p> {{ item.review_text }}</p>
            </div>
            <hr style="opacity: 0">
            <div class="book-details">
                <h3>Détails de {{ book.title }}</h3>
                <p>Auteur : <b>{{ book.author}}</b></p>
                <p>Parution en <b>{{ book.date}}</b></p>
                <img alt="Book cover" class="book_cover_details" src="{{ book.book_cover.url }}">
            </div>

    </main>
{% endblock content %}

LITRevu/blog/templates/blog/create_ticket.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-creation-form">
        <h2>Création de ticket - demande de critique</h2>
        <h3>Livre</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Enregistrer la demande</button>
        </form>
    </div>
{% endblock content %}

LITRevu/blog/templates/blog/delete_ticket.html
{% extends 'base.html' %}
{% block content %}
<h2>Suppression de ticket - demande de critique</h2>
<h3>Livre</h3>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ book.title }}
    {{ book.author }}
    {{ book.date }}
    <p>
        {{ form.as_p }}
    </p>
    <button type="submit">Supprimer</button>
</form>
{% endblock content %}

LITRevu/blog/templates/blog/edit_review.html
{% extends 'base.html' %}
{% block content %}
<h2>Modification de Review</h2>
<h3>Livre</h3>
    <p>submitted by {{ book.submitted_by_id }}</p>
    <p>current user : {{ current_user }}</p>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% if book.submitted_by == current_user %}
        <p>{{ book_form.as_p }}</p>
    {% endif %}
    <p>{{ review_form.as_p }}</p>
    <button type="submit">Enregistrer la review</button>
</form>
{% endblock content %}

LITRevu/blog/templates/blog/edit_ticket.html
{% extends 'base.html' %}
{% block content %}
<h2>Modification de ticket - demande de critique</h2>
<h3>Livre</h3>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ ticket.book }}
    {{ ticket.book.author }}
    {{ ticket.date }}
    <p>
        {{ form.as_p }}
    </p>
    <button type="submit">Enregistrer la demande</button>
</form>
{% endblock content %}

LITRevu/blog/templates/blog/explore_db.html
{% extends 'base.html' %}
{% block content %}
<h2>Liste des objets vraiment créés</h2>
<h3>Livres</h3>
{% for book in books %}
    <p>{{ book.title }}</p>
    <p>{{ book.date }}</p>
    <p>{{ book.author }}</p>
    <img src="{{ book.book_cover.url }}">
    <hr>
{% endfor %}
<h3>Tickets</h3>
{% for ticket in tickets %}
    <p>{{ ticket.author }}</p>
    <p>{{ ticket.date }}</p>
    <p>{{ ticket.book.title }}</p>
    <hr>
{% endfor %}
{% for review in reviews %}
    <p>{{ review.book }}</p>
    <p>{{ review.date }}</p>
    <hr>
{% endfor %}
{% endblock content %}

LITRevu/blog/templates/blog/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load custom_filters %}
<div class="home">
    <h2>Feed</h2>
    {% for item in feed %}
        <div class="feed_item">
            <div class="intro">
            {% if item.0.author == user %}
                <div class="crud">
                {% if item.1 == "ticket" %}
                    <a href="{% url 'edit_ticket' item.0.id item.0.book.id %}">Modifier ticket ?</a>
                {% elif item.1 == "review" %}
                    <a href="{% url 'edit_review' item.0.id item.0.book.id %}">Modifier review ?</a>
                {% endif %}
                    <form action="{% url 'delete_item' item.1 item.0.id %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="item_to_delete" value="{{ item.0.id }}, {{ item.1 }}">
                        <button type="submit" >Supprimer</button>
                    </form>
                </div>
            {% endif %}
                {% if item.1 == "ticket" %}
                    <span class="label" style="background-color:#E1341E;">ticket</span><a href="{% url 'item_details' item.1 item.0.id %}"><div><b>{{ item.0.author }}</b> a publié un ticket :</div></a>
                {% elif item.1 == "review" %}
                    <span class="label" style="background-color:#1697a7;">critique</span><a href="{% url 'item_details' item.1 item.0.id %}"><div><b>{{ item.0.author }}</b> a publié une critique :</div></a>
                {% endif %}
            </div>
                <p class="timestamp"><i>{{ item.0.date }}</i></p>
                <p>{% if item.1 == "review" %}
                    {% for rank in item.0.rating|get_range %}
                        <object type="image/svg+xml" data="{% static 'yellow-star.svg' %}"></object>
                    {% endfor %}
                    {% for rank in item.0.rating|get_range_two_values:5 %}
                        <object type="image/svg+xml" data="{% static 'grey-star.svg' %}"></object>
                    {% endfor %}
                    <b>{{ item.0.review_title }}</b>
                {% endif %}</p>
                {% if item.0.ticket %}
                    <div class="ticket-response">
                        <div class="original-post">
                            <p><span class="label" style="background-color:#E1341E;">ticket</span><b>{{ item.0.ticket.author }}</b></p>
                            <p>{{ item.0.ticket }}</p>
                            <p><img alt="book cover" src="{{ item.0.book.book_cover.url }}"></p>
                        </div>
                        <p>{{ item.0.review_text }}</p>
                    </div>
                {% else %}
                    <p><b>{{ item.0 }}</b> de {{ item.0.book.author }}</p>
                    <div class="review-abstract">
                        <p><img alt="book cover" src="{{ item.0.book.book_cover.url }}"></p>
                        <p class="review-abstract-text">{{ item.0.review_text }}</p>
                    </div>
                {% endif %}
                {% if item.1 == "ticket" and item.0.author != user %} <!-- Ne pas pas s'auto-répondre -->
                    <a class="ticket-response-button" href="{% url 'create_review_answer_ticket' item.0.book.id item.0.id %}">Répondre</a>
                {% endif %}
    </div>
    {% endfor %}
</div>
{% endblock content %}

LITRevu/blog/templates/blog/isolated_book_form.html
{{ form.as_p }}

LITRevu/blog/templates/blog/relations.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="home">
<div class="search-card">
    <h2>Rechercher un membre</h2>
    <form>
        {{ search_form.as_p }}
    </form>
    <div class="user-list">
    </div>
</div>
    <h2>Liste des membres:</h2>
    <div class="user-list">
    {% for user in sorted_users %}
        {% if user not in blocked_by %}
            <div><p>{{ user.username }}</p>
                <section class="user_relations_buttons">
                    {% if user not in followed_users and user not in blocked_users %}
                        <form action="{% url 'follow_unfollow' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="follow">Suivre</button>
                        <input type="hidden" name="user_to_verify" value="{{ user.id }}"/>
                        </form>
                    {% elif user in followed_users %}
                        <form action="{% url 'follow_unfollow' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" style="background-color: #027373;color: white;">Suivi(e)</button>
                        <input type="hidden" name="user_to_verify" value="{{ user.id }}"/>
                        </form>
                    {% else %}
                    {% endif %}
                    {% if user not in blocked_users %}
                        <form action="{% url 'block_unblock' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="follow">Bloquer</button>
                        <input type="hidden" name="user_to_verify" value="{{ user.id }}"/>
                        </form>
                    {% elif user in blocked_users %}
                        <form action="{% url 'block_unblock' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" style="background-color: #027373;color: white;">Débloquer</button>
                        <input type="hidden" name="user_to_verify" value="{{ user.id }}"/>
                        </form>
                    {% endif %}
                </section>
            </div>
            {% endif %}
    {% endfor %}
    </div>
<!-- Membres suivis -->
{% if followed_users %}
    <h2>Membres suivis :</h2>
    <div class="user-list">
    {% for user in followed_users %}
        <div>
            <p>{{ user.username }}</p>
            <section>
                <form action="{% url 'follow_unfollow' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Ne plus suivre</button>
                    <input type="hidden" name="user_to_verify" value="{{ user.id }}"/>
                </form>
            </section>
        </div>
    {% endfor %}
    </div>
{% endif %}
<!-- fin Membres suivis -->

<!-- Membres bloqués -->
{% if blocked_users %}
    <h2>Membres bloqués :</h2>
    <div class="user-list">
    {% for user in blocked_users %}
        <div>
            <p>{{ user.username }}</p>
            <section>
                <form action="{% url 'block_unblock' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" style="background-color: #027373;color: white;">Débloquer</button>
                    <input type="hidden" name="user_to_verify" value="{{ user.id }}"/>
                </form>
            </section>
        </div>
    {% endfor %}
    </div>
{% endif %}
<!-- fin Membres bloqués -->

<!-- Membres abonnés -->
{% if followed_by %}
    <h2>Membres abonnés :</h2>
    <div class="user-list">
    {% for user in followed_by %}
        <div>
            <p>{{ user.username }}</p>
            <section>
                <form action="{% url 'stop_following_me' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Supprimer</button>
                    <input type="hidden" name="user_to_verify" value="{{ user.id }}"/>
                </form>
                <form action="{% url 'block_unblock' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Bloquer</button>
                    <input type="hidden" name="user_to_verify" value="{{ user.id }}"/>
                </form>
            </section>
        </div>
    {% endfor %}
    </div>
{% endif %}
<!-- fin Membres abonnés -->
</div>
    <script type="text/javascript">
        let inputSearch = document.querySelector('#id_search')
        let searchResults = document.querySelector('.user-list')
        inputSearch.addEventListener("keyup", function(){
            let searchValue = encodeURIComponent(inputSearch.value);
            let url = `/search_users/?search=${searchValue}`
            fetch(url, {
                    method: 'GET',
                    headers: {
                      'Accept': 'application/json',
                      'Content-Type': 'application/json'
                    }
                }
            )
            .then((response) => response.json())
            .then((data) => {
                searchResults.innerHTML = '';

                if (searchValue === '') {
                    return;
                }

                data.users.some((user) => {
                    console.log(user)
                    let userElement = document.createElement('div')
                    userElement.classList.add('searchResultDiv')

                    userElement.innerHTML = `


            <p>${user.username}</p>
                <section class="user_relations_buttons">
                    <form action="{% url "follow_unfollow" %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="follow">Follow / Unfollow</button>
                    <input type="hidden" name="user_to_verify" value="${user.id}"/>
                    </form>
                    <form action="{% url "block_unblock" %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="follow">Bloquer / Débloquer</button>
                    <input type="hidden" name="user_to_verify" value="${user.id}"/>
                    </form>
                </section>


`;
                    console.log(user.username)
                    searchResults.appendChild(userElement);

                    return true;
                })
                console.log(data)
            })
        })

    </script>
{% endblock content %}

LITRevu/blog/templates/blog/review_confirmation.html
{% extends 'base.html' %}
{% block content %}
<h2>Ticket créé !</h2>
{% csrf_token %}

<p>Vous avez créé une demande de critique à propos du livre ci-dessous :</p>
<p>{{ book.title }}</p>
<p>de {{ book.author }}</p>
<img src="{{ book.book_cover.url }}">
<p>paru en {{ book.date }}</p>
{% endblock content %}

LITRevu/blog/templates/blog/ticket_confirmation.html
{% extends 'base.html' %}
{% block content %}
<h2>Ticket créé !</h2>
{% csrf_token %}

<p>Vous avez créé une demande de critique à propos du livre ci-dessous :</p>
<p>{{ book.title }}</p>
<p>de {{ book.author }}</p>
<img src="{{ book.book_cover.url }}">
<p>paru en {{ book.date }}</p>
{% endblock content %}